# Generated by Django 4.2.1 on 2023-05-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_stock_quantity_stock_amount_invested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
