# Generated by Django 4.2.1 on 2023-05-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
