# Generated by Django 4.2.1 on 2023-05-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_stock_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="current_value",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
